name: Mot3lqat
description: Flutter app that verifies and saves credit cards.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.24.0
  cupertino_icons: ^1.0.6
  country_picker: ^2.0.25
  firebase_auth: ^4.15.0

  flutter_localizations:
    sdk: flutter
  credit_card_validator: ^2.1.0
  flip_card: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mlkit_text_recognition: ^0.11.0
  image_picker:

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/src/img/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/src/img/icon.png